FORMAT: 1A
HOST: http://factual.ro/api/

# Fact-checker API

Fact-checker API is a simple API allowing acccess to the database of fact-checked statements.

## Authentication
Some *Fact-checker API* endpoints do not require authentication while others do:

* The query facts endpoint should **not** require authentication. It will
be used by the browser extension and the website widget.
* All other endpoints will require authentication. They will be used to
build tools to enable easier association of facts to URIs.

The priority, for now, are the unautenthicated enpoints. All the others
are just ideas at the moment to allow the development of tools for easier
updating and association of URIs with already existing facts. Since the
tools are just an idea we should not focus on them immediately.

## Request format

Requests with a message-body are using plain JSON (application/json) to
set or update resource states.

## Error States

The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md)
are used.

## Group Statements

Statement is a claim made by politician (or organization) that has been fact-checked.  

## Statement [/statements/{id}]

+ Parameters
    + id: 1 (required, string) - ID of the statement

+ Attributes (Statement Object)
    
### View specific statement [GET]

+ Response 200 (application/json)
    + Attributes (Statement)

## Statements list [/statements{?uri}{?client}{?origin}]

### Statements in given source [GET]

This endpoint will return all the statements that are associated with
the specified `uri`. If no `uri` parameter is set all the statements 
in the database will be returned.

+ Parameters
    + uri (optional, URI, `http://www.agerpres.ro/politica/2016/07/10/dragnea-de-cand-e-gabriela-firea-primar-nu-s-a-taiat-niciun-pom-pe-kiseleff-21-41-07`) ... URI to check for a fact check.
    + client (optional, enum[string]) - Who is calling the statement list?
        + Members
            + chrome_extension
            + media_partner
    + origin (optional, enum[string]) - Where has user seen the highlight first and then navigated to the article?
        + Members
            + facebook
    
+ Response 200 (application/json)
    + Attributes (array[Statement Object])

## Group Sources

These are the sources of the statements that were fact-checked. 
They can include news articles or govermental websites, 
but also youtube video and other online sources.

## Sources list [/sources]

### List all sources [GET]

Lists URIs of all sources

+ Response 200 (application/json)
    + Attributes (array[string])


# Data Structures

## Statement Object (object)
+ id: 1 (string) - The id of the statement
+ text: We in Indiana have . . . the highest credit rating in the nation. (string) - The statement's text
+ person_name: Mike Pence (string) - A name of the person who said the statement
+ rating: false (string) - The rating of the statement: true | false | half-true. This dictionary depends on the fact-checker
+ explanation: Indiana Gov. Mike Pence, the Republican nominee for vice president, introduced himself... (string) - The extended explanation of the rating
+ factchecker_uri: http://www.politifact.com/truth-o-meter/statements/2016/jul/21/mike-pence/mike-pence-touts-top-indiana-credit-rating-achieve/ (string) - The URI of the fact check on fact-checker website
+ sources: http://www.agerpres.ro/politica/2016/07/10/dragnea-de-cand-e-gabriela-firea-primar-nu-s-a-taiat-niciun-pom-pe-kiseleff-21-41-07  (array[string])
